### ISSUE TITLE
Update "About"

### ISSUE THREAD

**Issue by adamhenriques** [Praqma/code-conf.com#93] opened 2016-04-12 15:06 UTC
Please update "About" on CoDeCPH;

if we can differentiate between the two pages, for starters use (and please update/ellaborate;

**CoDeCPH**
"The CoDe conference brings together technologists and industry leaders and focuses on innovation through Continuous Delivery and DevOps.
This full day conference explores the multi-faceted area of CoDe, how IT influences the triple bottom line and what Continuous Delivery and DevOps really mean to businesses and how it can be achieved.
Together we’ll be exploring the area of CoDe covering the entire Continuous Delivery Storyline and the many changes that impact how to produce and deliver quality software today."

**Day of Containers**
"
Day Of Containers is a full day festival focused on hands-on workshops and demos of the Docker ecosystem and the newest trends of containerization en general. Developers of all experience levels will learn about and get hands-on with all different aspects of Docker from introductory sessions on creating and running Docker containers, to advanced composition and orchestration in cloud environments."

**Comment by lakruzz** [comment] 2016-04-13 11:56
@monaslarsen this on needs an estimate (add a size label and remove the "needs grooming" label). Currently it's assigned to you, if it's yours then _please estimate it_, if someone else should implement it, then assign it to that person

**Comment by lakruzz** [comment] 2016-04-13 12:02
note: The about page is not about "CoDeCPH" or "Day of Containers" it's about www.code-conf.com.  So the story that needs to be told here is "What is code-conf all about?" (Continuous Delivery conferences, meetups, workshops and academies)

**Comment by lakruzz** [comment] 2016-04-13 12:50
Closing this a a duplicate of #54

**Comment by adamhenriques** [comment] 2016-04-13 12:53
@lakruzz now it says "About www.codeconf.com"

**Comment by lakruzz** [comment] 2016-04-13 13:01
Closing this one - taking it to: #95 and reopening #54 instead

**Closed by lakruzz** 2016-04-13 13:01 UTC
Labels: Prio 1 - must have, Status - duplicate
