### ISSUE TITLE
Meet-up: make header look good on mobile

### ISSUE THREAD

**Issue by illus0r** [Praqma/code-conf.com#255] opened 2016-06-10 13:32 UTC
Subtask of #251

![image](https://cloud.githubusercontent.com/assets/797993/15965826/d4edcb82-2f28-11e6-90e0-8cf5d2c40af4.png)

**Comment by lakruzz** [comment] 2016-06-15 13:52
duplicate of #254

**Closed by lakruzz** 2016-06-15 13:52 UTC
Labels: Size 1 - small, Status - duplicate
