### ISSUE TITLE
Design site footer so add some extra links there

### ISSUE THREAD

**Issue by illus0r** [Praqma/code-conf.com#135] opened 2016-04-27 13:57 UTC
Relates to #86 and #91 
There's no room it header for everything. ![](https://cloud.githubusercontent.com/assets/797993/14852073/dbcebb14-0c8c-11e6-89f6-9de0c54c7b70.png)
#86 wants to add **Call for papers** there as well.

> were gonna need a bigger boat

Candidates for moving to footer:
* Became a sponsor
* Call for papers (may be worth renaming?)
* Past events (ex. Archive)

**Comment by jonnycoull** [comment] 2016-04-27 13:59
@illus0r @adamhenriques @lakruzz 

before I do this id rather not double handle a task so lets make sure we have EVERYTHING that needs to go on the top and bottom of the site.  please list in the comments below.

**Comment by jonnycoull** [comment] 2016-04-27 16:25
Here we go, @illus0r this should please you. more separated menu. and for @adamhenriques a redesigned footer so additional links can be displayed. also more added if needs be now the logo is bottom right. buttons line up with top of logo. 

![screen shot 2016-04-27 at 17 23 40](https://cloud.githubusercontent.com/assets/17589853/14859661/11d96668-0c9d-11e6-8563-2d10ffb49bb0.png)

**Comment by jonnycoull** [comment] 2016-04-27 16:27
Or a thinner version of the top bar, @illus0r @adamhenriques 
![screen shot 2016-04-27 at 17 27 03](https://cloud.githubusercontent.com/assets/17589853/14859705/51519e32-0c9d-11e6-870c-6a78b24cfa61.png)

**Comment by illus0r** [comment] 2016-04-28 12:25
@lakruzz do we really need a search? What a possible scenario of it's usage? Or can we scale it down with no pain?

**Comment by lakruzz** [comment] 2016-04-28 14:49
No - I don't really need a search panel

**Comment by jonnycoull** [comment] 2016-04-28 16:14
@illus0r @lakruzz depending if you want the BIG menu bar or slightly thinner one, if theres no search bar ill have to redesign it again. As otherwise there will be an unsightly gap. Remember as much as you guys love your minimal products and coding this is a folio piece for the company so it needs to look good as well!

**Comment by illus0r** [comment] 2016-05-04 09:04
@lakruzz can I assign this back to @jonnycoull?

**Comment by jonnycoull** [comment] 2016-05-04 09:18
I think we should have it like it is, as we've got a ever ballooning amount of content in the site? @lakruzz @illus0r . my preference is the thinner one.

**Comment by illus0r** [comment] 2016-05-04 12:50
@jonnycoull 
1. sorry, I didn't get the idea, what do you mean by BIG and thinner? Anyway, there's no need in search bar 😀 
2. The footer links look confusing. I've never seen them being like buttons. What if we'll have to add 4 more links? 

`TWITTER`

![image](https://cloud.githubusercontent.com/assets/797993/15014491/08f9b116-120f-11e6-8309-5af010e6b2dc.png)

---

`UBUNTU`
![image](https://cloud.githubusercontent.com/assets/797993/15014536/41ee245c-120f-11e6-86c4-e8a0d4f55854.png)

---

`GOOGLE`
![image](https://cloud.githubusercontent.com/assets/797993/15014548/50f783d0-120f-11e6-9832-2b7edf52494d.png)

Or scroll down to see the github footer 😀 Everywhere links are links, not buttons.

**Comment by jonnycoull** [comment] 2016-05-04 15:43
ah i see where your confused. I've not done that very bottom bit yet thats
to come. those are buttons that are links.  they are more like that one on
twitter where its says CREATE AN ACCOUNT. like secondary important stuff.

**Comment by jonnycoull** [comment] 2016-05-04 16:31
@illus0r like this....also @adamhenriques expressed an interest in a newsletter button/sign up.

one with and thithout SEARCH. also placement of more in the menu bar at the top.

![codeconf_menu options_v3](https://cloud.githubusercontent.com/assets/17589853/15021298/ec7a2d90-121d-11e6-8757-c2a9eb81fc78.jpg)

**Comment by jonnycoull** [comment] 2016-05-04 16:32
The orange bits are the links. when highlighted. I know thats different to the others but lots of orange copy is bad on the eyes.

**Comment by illus0r** [comment] 2016-05-05 10:54
@jonnycoull 

1️⃣ 
Newsletter signup would be more simple if we add an action button (like `Sign up`). We can cut it out from current label. I'd like to know, what am I subscribing for. What will I receive? How often? If we can't write answers ourselves, we can ask somebody who knows. 
![image](https://cloud.githubusercontent.com/assets/797993/15041875/055d849c-12c8-11e6-891b-b081a8ffc2fb.png)
In our case: 
**Stay notified about new events!** [your@email.com       ][Subscribe] <sub>About 3 emails per month</sub>

2️⃣ 
![image](https://cloud.githubusercontent.com/assets/797993/15041167/9b9e39a2-12c2-11e6-8506-35243bdca9dd.png) The proper copyright format is 

- (c), 
- owner, 
- year of first publication. 

So in our case that's `© Praqma 2016`, in 2017 we can expand it to `© Praqma 2016—2017` and so on. Or we can remove that at all. `©` sign doesn't create or protect rights, it just informs and helps to find owner.

**Comment by lakruzz** [comment] 2016-05-05 12:36
Pay attention to #121 too - it's closed as a duplicate of this one

**Comment by jonnycoull** [comment] 2016-05-05 14:01
No worries @illus0r most copy on there is only for mock up purposes, ill let you and others take care of those details if thats cool. 

So updated mock up. now the blue bars isn't on the site thats just a note for you ivan, we need a rule that nothing will come within that blue bar in terms of distance to the footer containing sign up, praam logo and the rest. make sense? @lakruzz is happy with the idea so its now part of read for press next friday. Mainly so when displayed with sponsors at the bottom there is a nice gap between the two parts.

![codeconf_menu options_v4](https://cloud.githubusercontent.com/assets/17589853/15045405/322e1f22-12d2-11e6-9de6-278e27e6f7fd.jpg)

**Comment by lakruzz** [comment] 2016-05-16 09:27
I'm closing this one, no more  to discuss here, lets carry on in the implementation issues mentioned above.

**Closed by lakruzz** 2016-05-16 09:27 UTC
Labels: Action - awaiting feed-back, Prio 2 - should have, Size 0 - Briefing
