### ISSUE TITLE
Automatically mark graduated classes with a ribbon

### ISSUE THREAD

**Issue by jonnycoull** [Praqma/code-conf.com#301] opened 2016-06-30 11:12 UTC
HI @timea @illus0r we need a GRADUATION BANNER across completed code academies. as per @monaslarsen instructions. I've placed an PNG images/pages/academy2016/GRAD.png at this location and inc a rough mock here.

**Comment by jonnycoull** [comment] 2016-06-30 11:13
![screen shot 2016-06-30 at 12 07 10](https://cloud.githubusercontent.com/assets/17589853/16486334/fc5fb638-3ebb-11e6-9e7b-994a05b66947.png)

**Comment by jonnycoull** [comment] 2016-08-15 08:21
@timea @illus0r this is done now right?

**Comment by illus0r** [comment] 2016-08-16 10:23
@jonnycoull 
I didn't implement anything. I see it [on the single page](http://www.code-conf.com/academy2016/trd/)

Should it be automatized? We can add this strip regarding event type and due date.

![image](https://cloud.githubusercontent.com/assets/797993/17696028/74a51c42-63b4-11e6-86ee-f895a52cc291.png)

**Comment by jonnycoull** [comment] 2016-08-16 10:37
@illus0r someone did, yet that sounds like a good idea.

**Comment by illus0r** [comment] 2016-08-16 12:02
@jonnycoull 
All right, what else should be accomplished within this issue?
If nothing, I'll rename this issue accord to new task

**Comment by jonnycoull** [comment] 2016-08-16 12:05
@illus0r yes, and automatically on 
![screen shot 2016-08-16 at 13 04 35](https://cloud.githubusercontent.com/assets/17589853/17698275/0c2c64e2-63b2-11e6-83a5-b1e3bab58aa6.png)
that the banner should display on the sub menu also which is previous to this page (but a new one as the current one is the wrong way)

**Comment by jonnycoull** [comment] 2016-08-16 12:06
![gradforsubmenu](https://cloud.githubusercontent.com/assets/17589853/17698291/2fbb308c-63b2-11e6-8d48-bf44f4069ee2.png)

**Comment by jonnycoull** [comment] 2016-08-16 12:07
Ive uploaded that to codeconf images. @illus0r

**Comment by illus0r** [comment] 2016-08-16 12:20
mark
- [ ] the event headers
- [ ] items in subevents' menu
- [ ] items in *past events*

**Comment by illus0r** [comment] 2016-09-02 13:12
![image](https://cloud.githubusercontent.com/assets/797993/18204747/001d5788-7127-11e6-8ec6-6dfa639e7f75.png)

![image](https://cloud.githubusercontent.com/assets/797993/18204764/1744478c-7127-11e6-9c1a-506c893729ba.png)

![image](https://cloud.githubusercontent.com/assets/797993/18204926/0b1c23fc-7128-11e6-983e-c105e9ad22dc.png)

**Comment by illus0r** [comment] 2016-09-02 13:17
Oops, I see changes on main academy page only. I'll have a look on other devices

**Comment by illus0r** [comment] 2016-09-02 13:34
Weird! Looks like this include doesn't work as it should. On GH only, so I can't reproduce it.
https://github.com/Praqma/code-conf.com/blob/gh-pages/_includes/func/is_subevent.html

`Yes. But it doesn't build on THAT machine.` ©

**Comment by illus0r** [comment] 2016-09-02 13:37
And there's a bug, Oslo marked as graduated. I'll roll it back if I won't fix in in an hour

**Comment by illus0r** [comment] 2016-09-02 13:53
It still works on my local machine only. I have no idea what causes the problem.
Time run out, can I take some more?

**Comment by illus0r** [comment] 2016-09-02 13:53
@jonnycoull

**Comment by illus0r** [comment] 2016-09-06 12:50
Hi, @jonnycoull! What's your point about the last comment?

**Comment by jonnycoull** [comment] 2016-09-06 15:39
Hi @illus0r I think because it was hitting the copy in the black box so I
made a version that sloped the other way. But looks as tho u moved it down.
Thus solving it

**Closed** 2016-09-07 11:43 UTC
Labels: Action - awaiting feed-back, Size 2 - medium, Status - in progress

**Comment by illus0r** [comment] 2016-09-07 11:45
The thing was with site.true and site.false. 
GH doesn't read these variables but site.true_ and site.false_ are ok.
